# Importing Libraries

[Numpy Source 01](https://www.educba.com/what-is-numpy-in-python/),
[Numpy Source 02](https://www.javatpoint.com/numpy-tutorial),
[Numpy Source 03](https://techvidvan.com/tutorials/python-numpy-tutorial/),
[Numpy Source 04](https://medium.com/analytics-vidhya/introduction-to-numpy-16a6efaffdd7),
[Numpy Source 05](https://data-flair.training/blogs/python-numpy-tutorial/),
[Numpy Source 06](https://www.quora.com/In-Python-what-is-NumPy-How-is-it-used),
[Numpy Source 07](https://fgnt.github.io/python_crashkurs_doc/include/numpy.html),
[Numpy Source 08](https://towardsdatascience.com/a-hitchhiker-guide-to-python-numpy-arrays-9358de570121),
[Numpy Source 09](https://scipy-lectures.org/intro/numpy/array_object.html)

In [ ]:
# NumPy Python Standard Library içerisinde bulunan bir module değildir.
# NumPy module'unu import etmek için önce ; NumPy module'unu Python pip aracı ile install etmemiz gerekiyor. 
# "pip" aracı bize Standard Library'de bulunmayan module'leri/package'leri dışarıdan install etmeyi sağlar.
# Bilimsel hesaplamalar için kullanılır.
# Arrayler/çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar
# Numpy dizileri python listelerine benzer fakat hız ve işlevsellik açısından python listelerinden daha kullanışlıdır.
# Çünkü listeler her bir eleman için ayrı ayrı bilgi tutarken numpy array'leri elemanlarını sabitlenmiş tipe zorlar 
# bu da veri saklama açısından büyük bir kolaylık sağlar

In [1]:
#pip install numpy

In [1]:
import numpy as np

In [1]:
dir(np) #numpy icindeki methodlari gosterir

In [4]:
np.__version__

'1.23.5'

In [2]:
# np.__doc__   # np.arange.__doc__

# Numpy Array vs List

[Numpy Array vs List Source 01](https://blog.finxter.com/what-are-advantages-of-numpy-over-regular-python-lists/),
[Numpy Array vs List Source 02](https://numpy.org/doc/stable/user/whatisnumpy.html),
[Numpy Array vs List Source 03](https://python.plainenglish.io/python-list-vs-numpy-array-whats-the-difference-7308cd4b52f6),
[Numpy vs List Source 04](https://webcourses.ucf.edu/courses/1249560/pages/python-lists-vs-numpy-arrays-what-is-the-difference#:~:text=A%20numpy%20array%20is%20a,a%20tuple%20of%20nonnegative%20integers.&text=A%20list%20is%20the%20Python,contain%20elements%20of%20different%20types.),
[Numpy Array vs List Source 05](https://dev.to/chanduthedev/python-list-vs-numpy-array-3pjp),
[Numpy Array vs List Source 06](https://medium.com/analytics-vidhya/list-vs-numpy-comparision-35bf921588e9),
[Numpy Array vs List Source 07](https://stackoverflow.com/questions/15944171/python-differences-between-lists-and-numpy-array-of-objects),
[Numpy Array vs List Video Source 01](https://www.youtube.com/watch?v=mkbgEvUkSaM),
[Numpy Array vs List Video Source 02](https://www.youtube.com/watch?v=JtW_xGNDEJ8) &
[Numpy Array vs List Video Source 03](https://www.youtube.com/watch?v=C10KmAbCW6A)

## Comparing list and array by computation time

In [6]:
import time

In [ ]:
# Python'un time.time() fonksiyonu, sistem saati ile ilgili bir zaman bilgisini saniye cinsinden döndürür. 
# Bu zaman bilgisi, 1 Ocak 1970 Unix epokuna kadar geçen süre olarak hesaplanır. 
# Yani, time.time() fonksiyonu, 1 Ocak 1970'den itibaren geçen saniyelerin verir.

In [7]:
time.time() 

1680263112.500231

In [8]:
start = time.time()  
start

1680263115.8379645

In [9]:
time.time() - start  

2.546367645263672

In [11]:
size = 1000000

l1 = range(size)  #list deki range methodu ile icine verilen sayiya kadar bir list olusturduk
l2 = range(size)

a1 = np.arange(size) #np de arange() methodu icine verilen sayiya kadar bir array olusturduk
a2 = np.arange(size)

# a1= np.array(l1)
# a2= np.array(l2) # array imizi bu sekilde de olusturabilirdik

#python list
start = time.time()
result = [(x + y) for x, y in zip(l1, l2)]
print("python list took: ", (time.time()-start) ) 
# burada python in list lerde calisma hizini gormek icin bir islem yaptrdik

# numpy array
start = time.time()
result = a1 + a2
print("numpy took: ", (time.time() - start) )
# burada np in array lerde calisma hizini gormek icin ayni islemi yaptrdik
#NOT :Bu kisimda python list ile numpy array i karsilastirdik. Sonuc olarak list array e gore daha yavas

python list took:  0.2680187225341797
numpy took:  0.018001556396484375


## Comparing list and array by size

In [11]:
import sys  

In [12]:
sys.getsizeof(5) # sys.getsizeof(): Bir nesnenin bellekte kapladığı alanın boyutunu verir.

28

In [13]:
sys.getsizeof(99999999)

28

In [14]:
sys.getsizeof("a")

50

In [15]:
sys.getsizeof("aaaaaa")

55

In [16]:
l = range(1000)

print("size of one item in list :", sys.getsizeof(5)) 
print("size of all item in list :", sys.getsizeof(5) * len(l))

print("---" * 10)

a = np.arange(1000)

print("size of one item in array :", a.itemsize)
print("size of all items in array :", a.itemsize * a.size )

# array e göre listeler 7 kat fazla yer kaplamış

size of one item in list : 28
size of all item in list : 28000
------------------------------
size of one item in array : 4
size of all items in array : 4000


## Comparing list and array by advanced mathematical operations

In [17]:
a=[1,2,3,4]
b=[4,3,2,1]
ab=[]

for i in range(0, len(a)):
    ab.append(a[i]*b[i])
ab

In [ ]:
a = [1, 2, 3, 4]
b = [4, 3, 2, 1]
[i * j for i, j in zip(a, b)] # verilen iki list in elemanlarini ayni sirayla birbiri ile carptik

[4, 6, 6, 4]

In [19]:
a1=np.array(a)
b1=np.array(b)

In [20]:
a1 * b1

array([4, 6, 6, 4])

In [21]:
a1 * 10

array([10, 20, 30, 40])

In [22]:
a1 / 10

array([0.1, 0.2, 0.3, 0.4])

In [23]:
a1 + b1

array([5, 5, 5, 5])

In [24]:
a1 - b1

array([-3, -1,  1,  3])

# Create Array Methods

[Numpy Array Source 01](https://www.geeksforgeeks.org/python-arrays/),
[Numpy Array Source 02](https://thispointer.com/python-numpy-create-a-ndarray-from-list-tuple-or-list-of-lists-using-numpy-array/),
[Numpy Array Source 03](https://www.pluralsight.com/guides/different-ways-create-numpy-arrays),
[Numpy Array Source 04](https://stackoverflow.com/questions/33983053/how-to-create-a-numpy-array-of-lists/33987165),
[Numpy Array Source 05](https://towardsdatascience.com/the-ten-best-ways-to-create-numpy-arrays-8b1029a972a7),
[Numpy Array Source 06](https://blog.finxter.com/how-to-convert-a-list-to-a-numpy-array/),
[Numpy Array Video Source 01](https://youtu.be/MKOw9ATtVqE),
[Numpy Array Video Source 02](https://youtu.be/RQ0x6OHym3k)

## From a Python List

### array

NumPy, arrays-diziler ile çalışmak için kullanılır. NumPy’deki dizi nesnesine ndarray denir. array() işlevini kullanarak bir NumPy ndarray nesnesi oluşturabiliriz.

In [25]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [26]:
np.array(my_list)

array([1, 2, 3])

In [27]:
np.array([1, 2, 3])

array([1, 2, 3])

In [28]:
np.array([1, 2, 3], dtype = float)
# dtype methodu default olarak var aslinda default hali integer dir. 
# Biz float olmasini istersek bu sekilde yazariz
# -dtype 
# elemanlarin veri tipi demek bu. kapladigi boyut sayisiyla alakali
# hem integer hem float olabilir listede, formatini tek bir tipe cevirip homojen olarak saklanmasini sagliyor numpy
# hem integer hem float koyarsak, tipini float yapar
# numpy'lar homojen, tek bir veri tipine cevirerek saklama yapiyor.

array([1., 2., 3.])

In [29]:
my_list2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
my_list2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [30]:
my_array2 = np.array(my_list2)
my_array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
my

### shape & reshape
shape; Numpy array nesnesinin kaç satır ve sütundan oluştuğunu gösteren bir tupple nesnesi döndürür.

reshape; Numpy array’i yeniden şekillendirmek istediğimizde yani satır ve sütun sayısını değiştirmek istediğimizde reshape() metodunu kullanabiliriz.

In [31]:
my_array2.shape

(4, 3)

In [32]:
my_array2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
my_array2.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [34]:
my_array2.reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [35]:
my_array2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
a= my_array2.reshape(12).reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [37]:
a.shape

(3, 2, 2)

In [38]:
arr = np.arange(36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [39]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [40]:
arr.reshape(-1, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [41]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

### ndmin 
Bir numpy array oluşturulurken boyut sayısını belirtmek için kullanılır.

In [42]:
myList=list(range(0,48))

In [43]:
myArray=np.array(myList, ndmin=4)

In [44]:
myArray

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
          30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
          45, 46, 47]]]])

In [45]:
myArray.shape

(1, 1, 1, 48)

In [46]:
myArray2=myArray.reshape(2,3,4,2)   # 4 satır ve 2 sütundan oluşan 3 tane 2 boyutlu , 2 tane 3 boyutlu, 
myArray2

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11],
         [12, 13],
         [14, 15]],

        [[16, 17],
         [18, 19],
         [20, 21],
         [22, 23]]],


       [[[24, 25],
         [26, 27],
         [28, 29],
         [30, 31]],

        [[32, 33],
         [34, 35],
         [36, 37],
         [38, 39]],

        [[40, 41],
         [42, 43],
         [44, 45],
         [46, 47]]]])

In [47]:
myArray2.shape

(2, 3, 4, 2)

### dtype & astype
dtype, bir numpy dizisinin veri tipini belirlemek  ve öğrenmek için kullanılır.

astype ise, bir numpy dizisinin veri tipini dönüştürmek için kullanılır. 

In [48]:
my_int = np.array([1, 2, 3])
my_int

array([1, 2, 3])

In [49]:
my_int.dtype

dtype('int32')

In [50]:
my_float = np.array([1, 2, 3, 4.5])
my_float

array([1. , 2. , 3. , 4.5])

In [51]:
my_float.dtype

dtype('float64')

In [52]:
my_string = np.array([1, 2, 3, 4.5, "a"])
my_string

array(['1', '2', '3', '4.5', 'a'], dtype='<U32')

In [53]:
my_string.dtype

dtype('<U32')

In [54]:
x = np.array([1, 2], dtype=np.float64)
print(x)        
print(x.dtype)  

[1. 2.]
float64


In [55]:
newx = x.astype('i')

print(newx)        
print(newx.dtype)  

[1 2]
int32


In [56]:
arr = np.array([0, 1, 2])

newarr = arr.astype(bool)

print(newarr)        
print(newarr.dtype) 

[False  True  True]
bool
